# action.yml
name: 'arcaflow-container-toolkit-action'
description: 'Docker container runtime to use the official arcaflow-container-tookit'
author: Arcalot
branding:
  icon: 'box'
  color: 'white'
  
inputs:
  image_name:  
    description: 'Name of plugin image to be built'
    required: true
    default: 'all'
  image_tag:  
    description: 'Tag of plugin image to be built'
    required: true
    default: 'latest'
  github_username:  
    description: 'Github username used to push image'
    required: false
    default: ''
  github_password:  
    description: 'Github password used to push image'
    required: false
    default: ''
  github_namespace:  
    description: 'Github namespaced used to push image'
    required: false
    default: ''
  quay_username:  
    description: 'Quay username used to push image'
    required: false
    default: ''
  quay_password:  
    description: 'Quay password used to push image'
    required: false
    default: ''
  quay_namespace:  
    description: 'Quay namespace used to push image'
    required: false
    default: ''
  quay_custom_namespace:  
    description: 'Quay custom namespace used to push image that is not QUAY_NAMESPACE'
    required: false
    default: ''
  quay_img_exp:  
    description: 'Image label to automatically delete image in quay'
    required: false
    default: 'never'
  build_timeout:  
    description: 'Lenth of time before build failure'
    required: false
    default: 600
  archetype:
    description: 'Architecture requested'
    required: false
    default: ''
  req_check_only:
    description: 'Utilize ACT only for requirements check'
    required: false
    default: false
  
runs:
  using: 'docker'
  image: 'docker://ghcr.io/arcalot/arcaflow-container-toolkit:v2.0.0'
  args:
    - 'build' 
    - '--build'
    - '--push'
  env:
    IMAGE_NAME: ${{ inputs.image_name }}
    IMAGE_TAG: ${{ inputs.image_tag }}
    GITHUB_USERNAME: ${{ inputs.github_username }}
    GITHUB_PASSWORD: ${{ inputs.github_password }}
    GITHUB_NAMESPACE: ${{ inputs.github_namespace }}
    QUAY_USERNAME: ${{ inputs.quay_username }}
    QUAY_PASSWORD: ${{ inputs.quay_password }}
    QUAY_NAMESPACE: ${{ inputs.quay_namespace }}
    QUAY_CUSTOM_NAMESPACE: ${{ inputs.quay_custom_namespace }}
    QUAY_IMG_EXP: ${{ inputs.quay_img_exp }}
    BUILD_TIMEOUT: ${{ inputs.build_timeout }}
    ARCHETYPE: ${{ inputs.archetype }}
    REQ_CHECK_ONLY: ${{ inputs.req_check_only }}
